# Generated by Django 3.2 on 2021-04-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0002_auto_20210429_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawlid', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('ready', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
            ],
        ),
    ]
