# Generated by Django 3.2 on 2021-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlstate',
            name='urlid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddConstraint(
            model_name='crawlstate',
            constraint=models.UniqueConstraint(fields=('url', 'crawlid'), name='unique_url_for_crawl'),
        ),
    ]
