# Generated by Django 3.2 on 2021-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20210503_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlstate',
            name='crawlid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
