# Generated by Django 3.2 on 2021-04-29 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
