# Generated by Django 3.2 on 2021-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_alter_container_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy', models.BooleanField(default=False)),
                ('feats', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('containerid', models.IntegerField(null=True)),
            ],
        ),
    ]
