# Generated by Django 3.2.2 on 2021-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_featuresstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
