# Generated by Django 3.2.2 on 2021-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_alter_container_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresstatus',
            name='computing_dendrogram',
            field=models.BooleanField(default=False),
        ),
    ]
