# Generated by Django 3.2 on 2021-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210506_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='seed',
            field=models.BooleanField(default=False),
        ),
    ]
