# Generated by Django 3.2.2 on 2021-05-09 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='hostname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='link',
            name='hostname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
